// src/app/components/product/product.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Product } from 'src/app/models/product';

@Component({
  selector: 'app-product',
  templateUrl: './product.component.html',
  styleUrls: ['./product.component.css']
})
export class ProductComponent implements OnInit {
  @Input() product: Product | undefined;
  imagePath: string = "";

  constructor() { }

  ngOnInit(): void {
    this.imagePath = this.product?.imagePath ?? '';
  }

}

<div class="card space shadow-sm" [routerLink]="'product/' + product?.id">
  <div class="card-body">
    <h4 class="card-title">{{ product?.name}}</h4>
    <img [src]="imagePath" alt="{{ product?.name }}" class="img-responsive float-end card-img">
    <div class="card-text">
      <p>{{product?.description}}</p>
      <p>$ {{product?.price}}</p>
      <span [innerHTML]="product?.imageDescription"></span>
    </div>
  </div>
</div>

// src/Components/product.jsx
import React, { Component } from 'react';

const Product = props => {
    return (
        <React.Fragment>
            <div className="card space shadow-sm">
                <div className="card-body">
                    <h4 className="card-title">{ props.name}</h4>
                    <img src="{props.imagePath}" alt="{ props.name }" className="img-responsive float-end card-img" />
                    <div className="card-text">
                        <p>{props.description}</p>
                        <p>$ {props.price}</p>
                        <span>{props.imageDescription}</span>
                    </div>
                </div>
            </div>
        </React.Fragment>
    );
};

export default Product;
