// src/app/components/product-page/product-page.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { Product } from 'src/app/models/product';
import { Size } from 'src/app/models/size';
import { ProductService } from 'src/app/service/product.service';

@Component({
  selector: 'app-product-page',
  templateUrl: './product-page.component.html',
  styleUrls: ['./product-page.component.css']
})
export class ProductPageComponent implements OnInit {
  product: Product | undefined;
  imagePath: string = "";
  price: number = 0;

  constructor(private productService: ProductService, private route: ActivatedRoute) { }

  ngOnInit(): void {
    this.getProduct();
  }

  getProduct(): void {
    const id = Number(this.route.snapshot.paramMap.get('id'));

    this.productService.getProduct(id).subscribe((p) => {
      this.product = p;
      this.imagePath = p?.imagePath || '';
      this.price = p?.price || 0;
    }
    );
  }
  onSizeChange(size: any) {
    if (this.product?.price !== undefined)
    switch (size) {
      case Size.MEDIUM: {
        this.price = this.product.price * 1.2;
        break;
      }
      case Size.LARGE: {
        this.price = this.product.price * 1.5;
        break;
      }
      default:
        this.price = this.product.price;
    }
  }

}

<div class="card space shadow-sm">
  <div class="card-body">
    <h4 class="card-title">{{ product?.name}}</h4>
    <img [src]="imagePath" alt="{{ product?.name }}" class="img-responsive float-end card-img">
    <div class="card-text">
      <p>{{product?.description}}</p>
      <p>$ {{ price.toFixed(2)}}</p>
      <mat-form-field appearance="fill">
        <mat-label>Choose Size:</mat-label>
          <mat-select
            (selectionChange) = "onSizeChange($event.value)">
            <mat-option *ngFor="let size of product?.size" [value]="size">{{ size }}</mat-option>
          </mat-select>
      </mat-form-field>
      <p [innerHTML]="product?.imageDescription"></p>
      <button
      [attr.data-item-id]="product?.id"
      [attr.data-item-name]="product?.name"
      [attr.data-item-description]="product?.description"
      [attr.data-item-price]="price"
      [attr.data-item-image]="imagePath"
      class="btn btn-primary snipcart-add-item">Add to Cart</button>
    </div>
  </div>
</div>

// src/Components/productpage.jsx
import React from 'react'
import axios from 'axios';


class productpage extends React.Component {
    state = { product: [], };
    server = "http://localhost:3001/products"
    componentDidMount = () => {
        const id = this.props.match.params.id;
        axios
            .get(this.server + "/" + id)
            .then((res, err) => {
                const product = res.data;
                this.setState({ product });
            });
    };
    render() {
        return (
            <React.Fragment>
                <div className="card space shadow-sm">
                    <div className="card-body">
                        <h4 className="card-title">{this.state.product.name}</h4>
                        <img src={this.state.product.imagePath} alt={this.state.product.name} className="img-responsive float-end card-img" />
                        <div className="card-text">
                        <p>{this.state.product.description}</p>
                        <p>$ {this.state.product.price}</p>
                        <p dangerouslySetInnerHTML={{__html: this.state.product.imageDescription }}></p>
                            <button
                            className="btn btn-primary snipcart-add-item"
                            data-item-id={this.state.product.id}
                            data-item-name={this.state.product.name}
                            data-item-description={this.state.product.description}
                            data-item-price={this.state.product.price}
                            data-item-image={this.state.product.imagePath}
                            data-item-custom1-name="Sies"
                                data-item-custom1-options="Small|Medium[+3]|Large[+5]">Add to Cart</button>
                            <p></p>
                        <p>To select your sizes please add to cart</p>
                        </div>
                    </div>
                </div>
            </React.Fragment>
        );
    };
}

    export default productpage;
